- name: Ensure arr_stack network exists or created to make arr trafic pass through it
  community.docker.docker_network:
    name: arr_stack
    state: present

- name: Render docker-compose file for gluetun
  template:
    src: docker-compose.yml.j2
    dest: "{{ __gluetun_compose_path }}"
    owner: root
    mode: '0644'
  register: compose_template

- name: Ensure compose project is up
  community.docker.docker_compose_v2:
    project_src: "{{ gluetun_directory }}"
    state: present
  when: compose_template.changed
